=== asbjoern1982/mars-colonies/src/configurations/game.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Stage",
  "description": "A stage in Mars Colonies",
  "type": "object",
  "properties": {
    "materials": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {"type": "string"},
          "depletion_rate": {"type": "number"}
        },
        "required": ["name", "depletion_rate"]
      }
    },
    "practiceRun": {"type": "boolean"},
    "soundVolume": {"type": "number"},
    "shuffleParticipants": {"type": "boolean"},
    "roundLengthInSeconds":  {"type": "number"},
    "inventoryBonusLimit": {"type": "number"},
    "inventoryCriticalLimit": {"type": "number"},
    "chat": {
      "anyOf": [
        {
          "type": "array",
          "items": {"type": "string"}
        },
        {
          "type": "string",
          "pattern": "free|none"
        }
      ]
    },
    "allowDirectMessages": {"type": "boolean"},
    "tooltip": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "inventories|specializations|score"
      }
    },
    "trade_delay": {"type": "number"},
    "productionAmounts": {"type": "array", "items": {"type": "number"}},
    "tradeAmounts": {"type": "array", "items": {"type": "number"}},
    "players": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {"type": "string"},
          "inventory": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {"type": "string"},
                "amount": {"type": "number"}
              },
              "required": ["name", "amount"]
            }
          },
          "specializations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "input": {"type": "string"},
                "output": {"type": "string"},
                "gain": {"type": "number"},
                "production_delay": {"type": "number"}
              },
              "required": ["input", "output", "gain", "production_delay"]
            }
          }
        },
        "required": ["name", "inventory", "specializations"]
      }
    }
  },

  "required": ["materials",
    "practiceRun",
    "soundVolume",
    "shuffleParticipants",
    "roundLengthInSeconds",
    "inventoryBonusLimit",
    "inventoryCriticalLimit",
    "chat",
    "allowDirectMessages",
    "tooltip",
    "trade_delay",
    "players"
  ]
}

=== asbjoern1982/mars-colonies/src/configurations/steno/game-steno.json
{
  "materials": [
    {"name": "Luft", "depletion_rate": 1.7},
    {"name": "Vand", "depletion_rate": 1.7},
    {"name": "Mad", "depletion_rate": 1.7}
  ],
  "practiceRun": false,
  "soundVolume": 0,
  "shuffleParticipants": true,
  "roundLengthInSeconds":  600,
  "inventoryBonusLimit": 600,
  "inventoryCriticalLimit": 100,
  "chat": "free",
  "allowDirectMessages": true,
  "tooltip": ["inventories", "specializations"],
  "trade_delay": 0,
  "players": [
    {
      "name": "Elysium",
      "inventory": [
        {"name": "Luft", "amount": 1000},
        {"name": "Vand", "amount": 1000},
        {"name": "Mad", "amount": 1000}
      ],
      "specializations": [{
        "input": "Luft",
        "output": "Vand",
        "gain": 2,
      	"production_delay": 10
      }]
    },
    {
      "name": "Utopia",
      "inventory": [
        {"name": "Luft", "amount": 1000},
        {"name": "Vand", "amount": 1000},
        {"name": "Mad", "amount": 1000}
      ],
      "specializations": [{
        "input": "Vand",
        "output": "Mad",
        "gain": 2,
	      "production_delay": 10
      }]
    },
    {
      "name": "Isidis",
      "inventory": [
        {"name": "Luft", "amount": 1000},
        {"name": "Vand", "amount": 1000},
        {"name": "Mad", "amount": 1000}
      ],
      "specializations": [{
        "input": "Mad",
        "output": "Luft",
        "gain": 2,
	      "production_delay": 10
      }]
    }
  ]
}

=== asbjoern1982/mars-colonies/src/configurations/game-1_config.json
{
  "materials": [
    {"name": "Palladium", "depletion_rate": 1.111111111},
    {"name": "Selenium", "depletion_rate": 1.111111111},
    {"name": "Tungsten", "depletion_rate": 1.111111111}
  ],
  "practiceRun": true,
  "soundVolume": 0,
  "shuffleParticipants": true,
  "roundLengthInSeconds":  600,
  "inventoryBonusLimit": 600,
  "inventoryCriticalLimit": 100,
  "chat": "free",
  "allowDirectMessages": true,
  "tooltip": ["inventories", "specializations"],
  "trade_delay": 0,
  "players": [
    {
      "name": "Oceania Colony",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Palladium",
        "output": "Selenium",
        "gain": 4,
      	"production_delay": 10
      }]
    },
    {
      "name": "Eurasia Colony",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Selenium",
        "output": "Tungsten",
        "gain": 4,
	      "production_delay": 10
      }]
    },
    {
      "name": "Eastasia Colony",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Tungsten",
        "output": "Palladium",
        "gain": 4,
	      "production_delay": 10
      }]
    },
    {
      "name": "Africa Colony",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Palladium",
        "output": "Selenium",
        "gain": 4,
      	"production_delay": 10
      }]
    },
    {
      "name": "South America Colony",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Selenium",
        "output": "Tungsten",
        "gain": 4,
	      "production_delay": 10
      }]
    },
    {
      "name": "North America Colony",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Tungsten",
        "output": "Palladium",
        "gain": 4,
	      "production_delay": 10
      }]
    }
  ]
}

=== asbjoern1982/mars-colonies/src/configurations/game-0_config.json
{
  "materials": [
    {"name": "Palladium", "depletion_rate": 0},
    {"name": "Selenium", "depletion_rate": 0},
    {"name": "Tungsten", "depletion_rate": 0}
  ],
  "practiceRun": true,
  "soundVolume": 0,
  "shuffleParticipants": true,
  "roundLengthInSeconds":  600,
  "inventoryBonusLimit": 600,
  "inventoryCriticalLimit": 100,
  "chat": "free",
  "allowDirectMessages": true,
  "tooltip": ["inventories", "specializations"],
  "trade_delay": 0,
  "players": [
    {
      "name": "Oceania",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Palladium",
        "output": "Selenium",
        "gain": 1.5,
      	"production_delay": 10
      }]
    },
    {
      "name": "Eurasia",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Selenium",
        "output": "Tungsten",
        "gain": 1.5,
	      "production_delay": 10
      }]
    },
    {
      "name": "Eastasia",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Tungsten",
        "output": "Palladium",
        "gain": 1.5,
	      "production_delay": 10
      }]
    },
    {
      "name": "Africa",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Palladium",
        "output": "Selenium",
        "gain": 1.5,
      	"production_delay": 10
      }]
    },
    {
      "name": "South America",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Selenium",
        "output": "Tungsten",
        "gain": 1.5,
	      "production_delay": 10
      }]
    },
    {
      "name": "North America",
      "inventory": [
        {"name": "Palladium", "amount": 1000},
        {"name": "Selenium", "amount": 1000},
        {"name": "Tungsten", "amount": 1000}
      ],
      "specializations": [{
        "input": "Tungsten",
        "output": "Palladium",
        "gain": 1.5,
	      "production_delay": 10
      }]
    }
  ]
}
